Changes in Blog + early pull of styles changes
lajcf/ajcf pull request #104
Opened 2021-02-26 11:56 UTC by seimori

2021-02-26 20:49 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleContainer.tsx
> +        </div>
chaud pour créer un composant Article

2021-02-26 20:50 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +  console.log(contentSummary);
ptit oubli

2021-02-26 20:52 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +          )}
Créer un composant BlogLabels (également utilisé dans ArticleContainer actuellement)

2021-02-26 20:53 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
qu'est-ce que optionalDate ? j'imagine un createdAt "effectif" ? Ce serait bien de le renommer plus effectivement si pas trop galère

2021-02-26 21:06 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +import { SelectBlogCategoryOrLabel } from "./SelectBlogCategoryOrLabel";
Donner un nom explicitant la nature de composant React

2021-02-26 21:07 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +  const [selectedBlogCategoryOrLabel, setSelectedBlogCategoryOrLabel] = useState<BlogCategory | BlogLabel>();
chaud pour parler de la manière d'implémenter cette différenciation entre catégorie / label, elle est pas très claire dans mon esprit, notamment lorsque je run le site 
![Screenshot 2021-02-26 at 22 07 33](https://user-images.githubusercontent.com/28652231/109355110-08474400-787f-11eb-9166-f7a76125ab68.png)

2021-02-26 21:11 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/SelectBlogCategoryOrLabel.tsx
> +  const [showLabels, setShowLabels] = useState<boolean>(false); // TODO Is it the right scope?
effectivement je pense que ce n'est pas le bon scope ici, chaud pour parler de cette partie en pair programming :)

2021-02-26 21:13 UTC, Nicoowr commented on ajcf-new-site/components/Home/HomeComponents/CarouselComponents/CarouselContainer.tsx
> +export const CarouselContainer = ({ articles }: { articles: ArticlePreviewFragment[] }) => {
Très stylé le Carousel ! :D

2021-02-26 21:14 UTC, Nicoowr commented on ajcf-new-site/components/Home/HomeComponents/EspacesComponents/Espaces.tsx
>  export const Espaces = () => {
possible de renommer en EspacesContainer ?

2021-02-26 21:15 UTC, Nicoowr commented on ajcf-new-site/components/Home/Home.tsx
> +export const Home = ({ articles }: { articles: ArticlePreviewFragment[] }) => {
Possible de renommer en HomeContainer ?

2021-02-26 21:15 UTC, Nicoowr commented on ajcf-new-site/components/Layout/Banner/BannerContainer.tsx
> +  switch (pathname) {
smart :)

2021-02-26 21:19 UTC, Nicoowr requested changes
- J'ai runné le site, il prend forme jour après jour, très joli. Tu fais du bon taff Issei. Tu captes de mieux en mieux la logique fonctionnelle également :)
- Chaud pour parler de la partie BlogLabel / BlogCategory qui nécessite un peu de refacto (tu le sens sûrement toi aussi)
- Fais attention à la taille de tes pull requests, c'est assez difficile pour un peer reviewer de se plonger dans autant de fichiers d'un coup. Ici j'aurais bien séparé la logique du blog du styling

2021-02-27 12:16 UTC, seimori commented
> * J'ai runné le site, il prend forme jour après jour, très joli. Tu fais du bon taff Issei. Tu captes de mieux en mieux la logique fonctionnelle également :)
> * Chaud pour parler de la partie BlogLabel / BlogCategory qui nécessite un peu de refacto (tu le sens sûrement toi aussi)
> * Fais attention à la taille de tes pull requests, c'est assez difficile pour un peer reviewer de se plonger dans autant de fichiers d'un coup. Ici j'aurais bien séparé la logique du blog du styling

* Oh merci! C'est fou comme le style à la fin change beaucoup de chose en perception :)
* Oui faut que je revois ça. Ça a été une demande de Madame UX, je l'ai implémanté assez vite pour que ce soit prêt avant la réunion de présentation du Blog.
* De mon côté aussi, j'aurais fait cette séparation. À la base j'avais une branche style et une branche blog. J'ai rushé pour avoir la version du site la plus aboutie possible sur dev avant la réunion. Mais c'est vrai que j'aurais dû faire une PR intermédiaire. Merci d'avoir fait une review de qualité malgré ça en tout cas ^^

2021-02-27 12:21 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleContainer.tsx
> +        </div>
J'ai du mal à le voir. Tu veux un composant article pour le "Content"?

2021-02-27 12:22 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +  console.log(contentSummary);
Oups :D

2021-02-27 13:44 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +          )}
Ah oui c'est bien mieux!

2021-02-27 13:46 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
optionalDate c'était une demande suite à la réunion.
Ça permet de choisir soi-même une date de parution de l'article (surtout pour rétro-dater certains articles, notamment pendant la migration).
Si optionalDate n'est pas rempli, on se base sur createdAt à la place.

2021-02-27 13:46 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleContainer.tsx
> +        </div>
Pour tout la partie visible de l'article, cad ligne 17 à 38 :)

2021-02-27 13:46 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
Est-ce que tu penses qu'il y a quelque chose à changer dans mon implémentation vu ce contexte?

2021-02-27 15:48 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
non l'implémentation est bonne, c'est plutôt le nom "optionalDate" qui est malheureux car on ne comprend pas tout de suite ce qu'il veut dire. Est-ce que "writtenDate" serait plus clair ?

2021-02-27 15:50 UTC, Nicoowr commented
> > * J'ai runné le site, il prend forme jour après jour, très joli. Tu fais du bon taff Issei. Tu captes de mieux en mieux la logique fonctionnelle également :)
> > * Chaud pour parler de la partie BlogLabel / BlogCategory qui nécessite un peu de refacto (tu le sens sûrement toi aussi)
> > * Fais attention à la taille de tes pull requests, c'est assez difficile pour un peer reviewer de se plonger dans autant de fichiers d'un coup. Ici j'aurais bien séparé la logique du blog du styling
> 
> * Oh merci! C'est fou comme le style à la fin change beaucoup de chose en perception :)
> * Oui faut que je revois ça. Ça a été une demande de Madame UX, je l'ai implémanté assez vite pour que ce soit prêt avant la réunion de présentation du Blog.
> * De mon côté aussi, j'aurais fait cette séparation. À la base j'avais une branche style et une branche blog. J'ai rushé pour avoir la version du site la plus aboutie possible sur dev avant la réunion. Mais c'est vrai que j'aurais dû faire une PR intermédiaire. Merci d'avoir fait une review de qualité malgré ça en tout cas ^^

D'ailleurs je te recommande chaudement ce plugin qui permet d'avoir la vue "file tree" dans github https://chrome.google.com/webstore/detail/better-pull-request-for-g/nfhdjopbhlggibjlimhdbogflgmbiahc

2021-02-28 00:44 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleContainer.tsx
> +        </div>
Oh! Je voyais pas l'intérêt tout de suite, mais t'as raison, c'est plus propre et logique

2021-02-28 00:47 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
Hmmm, tu trouves? J'ai l'impression que c'est moins clair pour les rédacteurs qu'ils ne sont pas obligés de remplir "writtenDate" dans leurs articles. À moins que je mette un nom différent pour GraphCMS et pour le code.
Je vais demander à Flora ce qu'elle en pense (pour le côté rédacteur)

2021-02-28 00:49 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +import { SelectBlogCategoryOrLabel } from "./SelectBlogCategoryOrLabel";
Hmm je suis désolé je ne comprends pas trop ce que tu veux dire :/

2021-02-28 00:52 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +  const [selectedBlogCategoryOrLabel, setSelectedBlogCategoryOrLabel] = useState<BlogCategory | BlogLabel>();
Oui moi aussi je trouve que c'est un peu confusant.
Flora voulait avoir une différenciations entres des catégories/rubriques et des labels/tags.
Les catégories c'est censé être plus large, comme de grandes parties dans un journal.
Les labels sont plus là pour marquer l'article thématiquement.

Tu penses que c'est la manière avec laquelle les filtres sont montrés qui participe le plus au manque de clarté?

2021-02-28 00:53 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/SelectBlogCategoryOrLabel.tsx
> +  const [showLabels, setShowLabels] = useState<boolean>(false); // TODO Is it the right scope?
Yes chaud de même!

À cet endroit ça provoquerait trop de re-render?

2021-02-28 00:53 UTC, seimori commented on ajcf-new-site/components/Home/HomeComponents/CarouselComponents/CarouselContainer.tsx
> +export const CarouselContainer = ({ articles }: { articles: ArticlePreviewFragment[] }) => {
Yeaaah merci!!!
J'en suis très fier ^^

2021-02-28 00:58 UTC, seimori commented on ajcf-new-site/components/Home/HomeComponents/EspacesComponents/Espaces.tsx
>  export const Espaces = () => {
Oui effectivement ça a plus de sens. Je fais de même pour tous les sous-éléments dans Home.tsx peut-être?
D'ailleurs je me demandais s'il fallait pas que je précise encore plus Espaces. HomeEspacesContainer?
Parce que la vraie partie Espaces est dans la partie Projets AJCF

2021-02-28 01:00 UTC, seimori commented on ajcf-new-site/components/Home/Home.tsx
> +export const Home = ({ articles }: { articles: ArticlePreviewFragment[] }) => {
Done!

2021-02-28 01:01 UTC, seimori commented on ajcf-new-site/components/Layout/Banner/BannerContainer.tsx
> +  switch (pathname) {
Héhé comme le QuickAccess :)

2021-02-28 01:05 UTC, seimori commented
> > > * J'ai runné le site, il prend forme jour après jour, très joli. Tu fais du bon taff Issei. Tu captes de mieux en mieux la logique fonctionnelle également :)
> > > * Chaud pour parler de la partie BlogLabel / BlogCategory qui nécessite un peu de refacto (tu le sens sûrement toi aussi)
> > > * Fais attention à la taille de tes pull requests, c'est assez difficile pour un peer reviewer de se plonger dans autant de fichiers d'un coup. Ici j'aurais bien séparé la logique du blog du styling
> > 
> > 
> > 
> > * Oh merci! C'est fou comme le style à la fin change beaucoup de chose en perception :)
> > * Oui faut que je revois ça. Ça a été une demande de Madame UX, je l'ai implémanté assez vite pour que ce soit prêt avant la réunion de présentation du Blog.
> > * De mon côté aussi, j'aurais fait cette séparation. À la base j'avais une branche style et une branche blog. J'ai rushé pour avoir la version du site la plus aboutie possible sur dev avant la réunion. Mais c'est vrai que j'aurais dû faire une PR intermédiaire. Merci d'avoir fait une review de qualité malgré ça en tout cas ^^
> 
> D'ailleurs je te recommande chaudement ce plugin qui permet d'avoir la vue "file tree" dans github https://chrome.google.com/webstore/detail/better-pull-request-for-g/nfhdjopbhlggibjlimhdbogflgmbiahc

Oh stylé!
J'imagine que c'est surtout en review que c'est hyper utile ^^

2021-02-28 11:27 UTC, Nicoowr commented
ça change la vie oui :p

2021-02-28 11:28 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/SelectBlogCategoryOrLabel.tsx
> +  const [showLabels, setShowLabels] = useState<boolean>(false); // TODO Is it the right scope?
Hmm je sais pas trop en fait il faut que j'aie une meilleur compréhension de ce système Lable/Category. Parlons-en de vive voix

2021-02-28 11:29 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +import { SelectBlogCategoryOrLabel } from "./SelectBlogCategoryOrLabel";
En fait SelectBlogCategoryOrLabel, on dirait le nom d'une fonction alors qu'ici c'est un composant. Il faudrait que le nom du composant ne porte pas cette confusion

2021-02-28 11:29 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
optionalWrittenDate alors ?

2021-02-28 11:31 UTC, Nicoowr commented on ajcf-new-site/components/Home/HomeComponents/EspacesComponents/Espaces.tsx
>  export const Espaces = () => {
Ah oui je plussoie !

2021-02-28 16:20 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
Du côté de Flora elle m'a dit qu'optionalDate avait été un bon nom pour les rédacteurs.
Quelle est l'information en plus apportée par "written"?
Je dis pas ça par méfiance, optionalWrittenDate me paraît être un compromis acceptable, c'est juste que j'ai du mal à voir ce que ça rajoute.

2021-02-28 16:20 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +import { SelectBlogCategoryOrLabel } from "./SelectBlogCategoryOrLabel";
Oh t'as raison. Certainement à cause du fait que ça commence par un verbe. Je vais tenté quelque chose d'autre

2021-02-28 16:21 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/SelectBlogCategoryOrLabel.tsx
> +  const [showLabels, setShowLabels] = useState<boolean>(false); // TODO Is it the right scope?
Ça marche!

2021-02-28 16:32 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +import { SelectBlogCategoryOrLabel } from "./SelectBlogCategoryOrLabel";
J'ai mis SelectorForBlogCategoryOrLabel qu'est-ce que t'en penses?

2021-02-28 16:34 UTC, seimori commented on ajcf-new-site/components/Home/HomeComponents/EspacesComponents/Espaces.tsx
>  export const Espaces = () => {
Je vais faire ces changements dans Style je pense. On est pas dans le scope de Blog :D
À moins que tu préfères que je fasse ça dans une branche pour Home?

2021-02-28 18:05 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
c'est juste que optionalDate donne pas d'info sur la signification de la date ("date optionnelle pour quoi")

2021-02-28 18:08 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +import { SelectBlogCategoryOrLabel } from "./SelectBlogCategoryOrLabel";
ouais c'est bien !

2021-02-28 18:09 UTC, Nicoowr commented on ajcf-new-site/components/Home/HomeComponents/EspacesComponents/Espaces.tsx
>  export const Espaces = () => {
on est plus à ça près haha tu peux le faire ici si tu veux

2021-02-28 18:09 UTC, Nicoowr commented on ajcf-new-site/components/Home/HomeComponents/EspacesComponents/Espaces.tsx
>  export const Espaces = () => {
sinon faudrait vraiment séparer Blog du reste

2021-02-28 18:10 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
après j'ai pas d'avis très fort làdessus tu peux laisser comme ça

2021-03-02 13:02 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
Qu'est-ce que tu penses de optionalPublishedDate?
C'est peut-être que moi, mais j'ai pas pensé immédiatement au fait que "written" voulait dire l'écriture de l'article

2021-03-02 13:07 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
oui parfait !

2021-03-02 13:38 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticlePreview.tsx
> +              {article.optionalDate ? dayjs(article.optionalDate).fromNow() : dayjs(article.createdAt).fromNow()})
Great! Ça vient d'être implémenté!

2021-03-02 13:40 UTC, seimori commented
Ça te va si on fait le squash and merge maintenant?
Il me semble que ce qu'il reste à régler se fait soit sur la branche style (pour le renommage des dépendances de Home) ou ce sont des choses conceptuelles à voir de vive-voix (blogCategory et blogLabel)

2021-03-02 13:46 UTC, Nicoowr commented
yes ok

2021-03-02 13:47 UTC, merged