enh(site): implement optionalPublishedDate for PressFiles
lajcf/ajcf pull request #118
Opened 2021-03-31 10:26 UTC by seimori

2021-04-02 16:25 UTC, Nicoowr commented on ajcf-new-site/components/APropos/Press/PressContainer.tsx
> +    ({ optionalPublishedDate, createdAt }) => optionalPublishedDate || createdAt,
destructuration dans une callback, sympa!

2021-04-02 16:25 UTC, Nicoowr commented on ajcf-new-site/components/APropos/Press/PressContainer.tsx
> +    ({ optionalPublishedDate, createdAt }) => optionalPublishedDate || createdAt,
c'est pas un pattern évident ^^

2021-04-02 16:25 UTC, Nicoowr commented on ajcf-new-site/components/APropos/Press/PressContainer.tsx
> +      <PressFiles pressFiles={orderedPressFiles.slice(0, 3)} title="Les plus récents" />
y a moyen de sortir le 3 dans une constante au début du fichier?

2021-04-02 16:26 UTC, Nicoowr requested changes
LGTM, un tout petit chgt!

2021-04-07 14:12 UTC, seimori commented on ajcf-new-site/components/APropos/Press/PressContainer.tsx
> +      <PressFiles pressFiles={orderedPressFiles.slice(0, 3)} title="Les plus récents" />
Oh yes ça a beaucoup de sens

2021-04-07 14:17 UTC, merged