style: Add QuickAccess
lajcf/ajcf pull request #51
Opened 2020-11-27 06:17 UTC by seimori

Est-ce que je fais de bien de faire un menu avec des Link?
Ou est-ce que je devrais gerer ca en changeant directement les composants React quand l'utilisateur clique sur les differentes categories?

2020-11-27 16:04 UTC, Nicoowr requested changes

2020-11-27 16:04 UTC, Nicoowr commented on ajcf-new-site/components/APropos/QuickAccess/QuickAccess.tsx
> +export const QuickAccess = ({ defaultSelectedKeys }: QuickAccessProps) => {
En effet, il faut mettre ce composant dans le layout, et celui-ci doit changer dynamiquement en fonction de l apage où on est. c'est + complexe mais je pense que c'est très intéressant à traiter !:D

2020-11-27 16:20 UTC, Nicoowr commented on ajcf-new-site/components/APropos/QuickAccess/QuickAccess.tsx
> +export const QuickAccess = ({ defaultSelectedKeys }: QuickAccessProps) => {
on pourra voir ça ensemble si besoin

2020-12-02 08:44 UTC, seimori commented
Voilà ma version de ce que tu m'as montré. Est-ce que je suis compatible avec les best-practices?

2020-12-02 09:31 UTC, Nicoowr requested changes
Globalement c'est bien !

2020-12-02 09:31 UTC, Nicoowr commented on ajcf-new-site/components/Layout/QuickAccess/QuickAccessContainer.tsx
> +  const page = dividedPathname.slice(-2, -1)[0] as Page;
chaud pour extraire ces lignes dans une fonction :)

2020-12-02 09:31 UTC, Nicoowr commented on ajcf-new-site/components/Layout/QuickAccess/QuickAccess.tsx
> +  defaultSelectedKeys: string[];
faudra qu'on fasse un truc pour typer string plus tard

2020-12-02 09:31 UTC, Nicoowr commented on ajcf-new-site/components/Layout/QuickAccess/QuickAccess.tsx
> +      {(() => {
je pense que c'est plus clair de mettre le switch au-dessus et de return dans le switch

2020-12-03 06:44 UTC, seimori commented on ajcf-new-site/components/Layout/QuickAccess/QuickAccess.tsx
> +  defaultSelectedKeys: string[];
Tu parles du string[] de defaultSelectedKeys?
Ou tu parles de string en général?

2020-12-03 07:08 UTC, seimori commented
Est-ce que c'est mieux comme ça? :)

2020-12-03 08:22 UTC, Nicoowr commented on ajcf-new-site/components/Layout/QuickAccess/QuickAccess.tsx
> +  defaultSelectedKeys: string[];
de defaultSelectedKeys :)

2020-12-03 08:25 UTC, Nicoowr commented on ajcf-new-site/components/Layout/QuickAccess/QuickAccessContainer.tsx
> +  const page = dividedPathname.slice(-2, -1)[0] as Page;
yes c'est bien comme ça ! ah oui un dernier truc !  page et subpage peuvent être undefined, ou ne pas correspondre à ce qu'on veut si par exemple ajoute des subsubpage.
2 possibilités : 
- tu réfléchis à une solution si tu as le temps 
- tu rajoutes un // TODO: take into account undefined case 
:D

2020-12-03 08:26 UTC, Nicoowr commented
J'ai ajouté une dernier commentaire :)

2020-12-03 08:26 UTC, Nicoowr commented
mais c'est bien sinon !

2020-12-03 16:31 UTC, seimori commented on ajcf-new-site/components/Layout/QuickAccess/QuickAccessContainer.tsx
> +  const page = dividedPathname.slice(-2, -1)[0] as Page;
J'ai essayé quelque chose, mais je suis pas du tout si je suis sur la bonne voie 😅

2020-12-03 16:47 UTC, seimori commented
Est-ce que ça va si j'appelle le quickaccess dans la subpage?
J'ai l'impression que je peux pas placer le menu comme dans le wireframe si je l'appelle directement dans Layout.tsx

2020-12-03 17:10 UTC, Nicoowr commented on ajcf-new-site/components/Layout/QuickAccess/QuickAccessContainer.tsx
> +  const page = dividedPathname.slice(-2, -1)[0] as Page;
à priori le undefined ne marchera pas, car on pourrait avoir un chemin comme ça : page/subpage/article, et le subpage serait défini
je pense que la bonne solution c'est de partir du début plutôt que de la fin :)

2020-12-03 17:11 UTC, Nicoowr commented on ajcf-new-site/components/Layout/QuickAccess/QuickAccessContainer.tsx
> +  const page = dividedPathname.slice(-2, -1)[0] as Page;
et de conserveer la gestion du cas undefined comme tu l'as fait

2020-12-03 17:11 UTC, Nicoowr commented
Hmmm faut qu'on en parle, parce que sinon on va devoir le rajouter partout :( 
mais mergeons en l'état , on en parlera de vive voix (tu peux rajouter un todo pour le sujet page/subpage)

2020-12-04 06:24 UTC, seimori commented on ajcf-new-site/components/Layout/QuickAccess/QuickAccessContainer.tsx
> +  const page = dividedPathname.slice(-2, -1)[0] as Page;
> à priori le undefined ne marchera pas, car on pourrait avoir un chemin comme ça : page/subpage/article, et le subpage serait défini
> je pense que la bonne solution c'est de partir du début plutôt que de la fin :)

Ah oui pas faux, je change ça!

2020-12-04 08:46 UTC, merged