ArticlePage
lajcf/ajcf pull request #72
Opened 2021-01-13 15:21 UTC by seimori

2021-01-13 15:46 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +    return filteredArticle.blogLabels.some((filteredArticleBlogLabel) =>
ici il s'agit de vérifier si l'intersection de 2 array est non vide, c'est un truc calcul assez classique, il faudra peut-être le refactoriser plus tard. Dans l'immdiat chaud pour extraire ça dans une fonction: `blogLabelsInCommon(...): boolean`

2021-01-13 15:46 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +    if (filteredArticle.id === article.id) return;
return false; 
car c'est plus idiomatique ^^

2021-01-13 15:47 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +  if (articleRecommendations.length <= 0) return <div />; // TODO: Check if there is a better way to return nothing
hmm ça va dépendre de l'UX demandée. Sinon on renvoie null ?

2021-01-13 15:47 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +const limitDisplayedArticles = (filteredArticles: ArticlePreviewFragment[], displayBuffer: number) => {
renommer displayBuffer

2021-01-13 15:48 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/formatContentSummary.tsx
> +export const formatContentSummary = (content: string, summaryLength: number) => {
bonne idée de refacto ça !

2021-01-13 15:48 UTC, Nicoowr requested changes
2 - 3 détails mais bien à part ça :D

2021-01-15 01:42 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +    if (filteredArticle.id === article.id) return;
Ah oui bonne idée!
J'avais oublié que je devais retourner un booléen à la mi-écriture de cette fonction 😅 
On dirait que ça prouve la nécessité de la refacto que tu m'as demandé plus haut :D

2021-01-15 01:45 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +  if (articleRecommendations.length <= 0) return <div />; // TODO: Check if there is a better way to return nothing
Oooh ça marche!
J'avais essayé de faire un retour sans rien, mais il me l'a refusé.
Il refuse undefined, mais il accepte null?

2021-01-15 01:53 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +const limitDisplayedArticles = (filteredArticles: ArticlePreviewFragment[], displayBuffer: number) => {
Oups effectivement!

2021-01-15 01:53 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/formatContentSummary.tsx
> +export const formatContentSummary = (content: string, summaryLength: number) => {
Héhé Merci ^^

2021-01-15 08:43 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +const blogLabelsInCommon = (filteredArticle: ArticlePreviewFragment, article: ArticlePageFragment) => {
Ici tu couples trop, càd que cette fonction n'est plus utilisable par exemple pour d'autres objets qui ont également des blogLabels. Si on veut aller encore plus loin, tu pourrais faire en sorte que cette fonction prenne en argument 2 tableaux de types génériques :p

2021-01-15 08:45 UTC, Nicoowr commented
Yep !

From: Issei Morimoto <notifications@github.com>
Date: Friday, 15 January 2021 at 02:46
To: lajcf/ajcf <ajcf@noreply.github.com>
Cc: Nicoowr <nicolas.li@hotmail.fr>, Review requested <review_requested@noreply.github.com>
Subject: Re: [lajcf/ajcf] ArticlePage (#72)

@seimori commented on this pull request.

________________________________

In ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx<https://github.com/lajcf/ajcf/pull/72#discussion_r557810832>:

> +import { ArticleContainerProps } from "./ArticleContainer";



+import { ArticleRecommendationPreview } from "./ArticleRecommendationPreview";



+



+const selectArticleRecommendations = ({ article, articles }: ArticleContainerProps) => {



+  const selectedArticles = articles.filter((filteredArticle) => {



+    if (filteredArticle.id === article.id) return;



+    return filteredArticle.blogLabels.some((filteredArticleBlogLabel) =>



+      article.blogLabels.includes(filteredArticleBlogLabel)



+    );



+  });



+  return selectedArticles;



+};



+



+export const ArticleRecommendations = ({ article, articles }: ArticleContainerProps) => {



+  const articleRecommendations = selectArticleRecommendations({ article, articles });



+  if (articleRecommendations.length <= 0) return <div />; // TODO: Check if there is a better way to return nothing



Oooh ça marche!
J'avais essayé de faire un retour sans rien, mais il me l'a refusé.
Il refuse undefined, mais il accepte null?

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/lajcf/ajcf/pull/72#discussion_r557810832>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AG2TFR7LNVD5BWI3RIIB2MLSZ6M5PANCNFSM4WA62OCQ>.

2021-01-16 00:18 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +const blogLabelsInCommon = (filteredArticle: ArticlePreviewFragment, article: ArticlePageFragment) => {
J'ai fait la version spécifiquement pour BlogLabel, ça ira?
Je suis étonné de pas avoir trouvé de fonction sur lodash permettant de faire le match avec des tableaux génériques. J'ai mal cherché?

2021-01-16 19:27 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +const blogLabelsInCommon = (filteredArticle: ArticlePreviewFragment, article: ArticlePageFragment) => {
ah si y a ça dans lodash : intersectionBy

2021-01-16 19:28 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +const isBlogLabelsMatch = (sourceBlogLabels: BlogLabel[], targetBlogLabels: BlogLabel[]) => {
essaie soit avec lodash (intersectionBy), soit avec des types génériques

2021-01-16 19:29 UTC, Nicoowr commented
Dès que tu auras utilisé intersectionBy ou des types génériques tu pourras merger !

2021-01-17 02:52 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +const isBlogLabelsMatch = (sourceBlogLabels: BlogLabel[], targetBlogLabels: BlogLabel[]) => {
J'ai opté pour les types génériques, j'ai regardé intersectionBy dans la doc de lodash, et j'avoue que je ne comprends pas trop le fonctionnement (chaud pour que tu me l'explique un jour! ^^).
J'étais pas tout à fait sûr du meilleur endroit pour mettre la fonction générique que j'ai crée. Est-ce que dans lib ça passe?

2021-01-17 12:48 UTC, Nicoowr requested changes

2021-01-17 12:48 UTC, Nicoowr commented on ajcf-new-site/lib/helperFunctions/arraysHaveMatch.ts
> +export const arraysHaveMatch = (sourceArray: Array<string>, targetArray: Array<string>) => {
c'est pas exactmeent ça :p 
Ecris plutôt : 
`const arraysShareElements = <T>(array1: T[], array2: T[]) > {
  // do something
}`

2021-01-17 12:48 UTC, Nicoowr commented on ajcf-new-site/lib/helperFunctions/arraysHaveMatch.ts
> +export const arraysHaveMatch = (sourceArray: Array<string>, targetArray: Array<string>) => {
Avec le `T` tu précises que cette fonction peut prendre n'importe quel type

2021-01-17 12:48 UTC, Nicoowr commented on ajcf-new-site/lib/helperFunctions/arraysHaveMatch.ts
> +export const arraysHaveMatch = (sourceArray: Array<string>, targetArray: Array<string>) => {
et que `array1` et `array2` doivent partager le même type

2021-01-17 12:49 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +const isBlogLabelsMatch = (sourceBlogLabels: BlogLabel[], targetBlogLabels: BlogLabel[]) => {
dans lib c'est bien ! j'appellerais plutôt le dossier `lib/utils`

2021-01-18 13:59 UTC, seimori commented on ajcf-new-site/lib/helperFunctions/arraysHaveMatch.ts
> +export const arraysHaveMatch = (sourceArray: Array<string>, targetArray: Array<string>) => {
Oh stylé cette syntaxe!
Plus j'en apprends sur TypeScript plus je trouve ça cool ^^

2021-01-18 14:01 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +const isBlogLabelsMatch = (sourceBlogLabels: BlogLabel[], targetBlogLabels: BlogLabel[]) => {
Dans lib/utils t'avais mis dayjs déjà.
Je pensais que garder les librairies extérieures dans un dossier à part serait mieux?

2021-01-18 14:28 UTC, Nicoowr commented on ajcf-new-site/lib/helperFunctions/arraysHaveMatch.ts
> +export const arraysHaveMatch = (sourceArray: Array<string>, targetArray: Array<string>) => {
^^

2021-01-18 14:29 UTC, Nicoowr commented
il faut que tu gères les conflits ^^

2021-01-18 14:30 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +const isBlogLabelsMatch = (sourceBlogLabels: BlogLabel[], targetBlogLabels: BlogLabel[]) => {
non tkt utilisons lib/utils pour toutes les fonctions utilitaires qui sont utilisées partout

2021-01-18 15:05 UTC, seimori commented on ajcf-new-site/components/Blog/BlogListComponents/ArticleRecommendations.tsx
> +const isBlogLabelsMatch = (sourceBlogLabels: BlogLabel[], targetBlogLabels: BlogLabel[]) => {
Ça marche :)

2021-01-18 15:06 UTC, seimori commented
> il faut que tu gères les conflits ^^

Je suis dessus, je regarde comment on fait avec Gitkraken

2021-01-18 15:11 UTC, merged

2021-01-18 15:12 UTC, seimori commented
J'ai mergé en local (et gérer les conflits comme ça) et pushé directement sur new-site.
Ça passe, ou j'aurais dû faire autrement?

2021-01-18 15:42 UTC, Nicoowr commented
c'est bien ça, tu gères les conflits en local et tu merge (pas push ^^)