Nos Espaces
lajcf/ajcf pull request #74
Opened 2021-01-19 12:46 UTC by seimori

2021-01-19 13:01 UTC, Nicoowr requested changes

2021-01-19 13:01 UTC, Nicoowr commented on ajcf-new-site/components/ProjetsAJCF/OurEspacesComponents/OurEspacesContainer.tsx
> +      <EspaceTalk />
Que dirais-tu de faire un fichier de "config", avec les `activitiesContent` et `espaceEnjoyContent` propres à chaque espace, et tu fais un map ici : 
`espaces.map(espace => <EspaceContent espace={espace} />`

2021-01-19 13:01 UTC, Nicoowr commented on ajcf-new-site/components/ProjetsAJCF/OurEspacesComponents/OurEspacesContainer.tsx
> +      <EspaceTalk />
c'est plus joli d'un point de vue déclaratif ^^

2021-01-19 19:34 UTC, Nicoowr approved these changes

2021-01-19 19:34 UTC, Nicoowr commented
j'ai approve ton dernier push, mais chaud pour traiter les points précédents ! ^^

2021-01-20 08:15 UTC, Nicoowr requested changes

2021-01-20 08:15 UTC, Nicoowr commented on ajcf-new-site/components/ProjetsAJCF/RecruitmentComponents/OurOffers.tsx
> +type offersContentProps = {
PascalCase

2021-01-20 13:52 UTC, seimori commented on ajcf-new-site/components/ProjetsAJCF/RecruitmentComponents/OurOffers.tsx
> +type offersContentProps = {
Aaah Pascaaaal!

2021-01-20 14:00 UTC, seimori commented on ajcf-new-site/components/ProjetsAJCF/OurEspacesComponents/OurEspacesContainer.tsx
> +      <EspaceTalk />
Ah oui j'avais hésité à faire ça!
Mais je me suis dit (peut-être à tort) qu'à long-terme il pourrait y avoir des cas de figures où ce serait nécessaire de modifier un espace dans sa présentation par rapport aux autres (par exemple l'espace enjoy qui mettrait un message pour dire que l'activité du pôle food est interrompu à cause de la crise sanitaire)

2021-01-20 14:00 UTC, seimori commented on ajcf-new-site/.gitignore
> +../.eslintcache
Oh nice!

2021-01-20 14:48 UTC, Nicoowr commented on ajcf-new-site/components/ProjetsAJCF/OurEspacesComponents/OurEspacesContainer.tsx
> +      <EspaceTalk />
C'est pas grave on changera le moment venu ^^

2021-01-20 15:08 UTC, seimori commented on ajcf-new-site/components/ProjetsAJCF/OurEspacesComponents/ActivitiesLogos.tsx
> +export const ActivitiesLogos = ({ activitiesContent }: { activitiesContent: ActivitiesContentProps[] }) => {
Est-ce que la manière avec laquelle je l'ai fait est la best-practice?

2021-01-20 16:05 UTC, Nicoowr commented on ajcf-new-site/components/ProjetsAJCF/OurEspacesComponents/ActivitiesLogos.tsx
> +export const ActivitiesLogos = ({ activitiesContent }: { activitiesContent: ActivitiesContentProps[] }) => {
non justement, car dans ta version `const Component = ({foo}: { foo: ComponentProps}) => {}

2021-01-20 17:20 UTC, Nicoowr commented on ajcf-new-site/components/ProjetsAJCF/OurEspacesComponents/ActivitiesLogos.tsx
> +export const ActivitiesLogos = ({ activitiesContent }: ActivitiesContentProps) => {
`ActivitiesLogosProps` :p quitte à le redéfinir ici

2021-01-20 17:21 UTC, Nicoowr commented on ajcf-new-site/components/ProjetsAJCF/OurEspacesComponents/ActivitiesLogos.tsx
> +export const ActivitiesLogos = ({ activitiesContent }: ActivitiesContentProps) => {
on en parle tout à lheure

2021-01-21 17:03 UTC, merged