Implementation of Agenda and Events
lajcf/ajcf pull request #85
Opened 2021-02-10 17:54 UTC by seimori

2021-02-10 21:09 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/AgendaComponents/EventPreview.tsx
> +            {additionalEventLabels?.map((label) => (
pas besoin de "?"

2021-02-10 21:14 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/AgendaComponents/EventsList.tsx
> +  const filterEvents = () => {
En faire une fonction pure

2021-02-10 21:19 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/EventComponents/FollowingEventPreview.tsx
> +export const FollowingEventPreview = ({ event }: FollowingEventProps) => {
Following -> Next

2021-02-10 21:21 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/EventComponents/FollowingEvents.tsx
> +  const filterFollowingEvents = () => {
fonction pure

2021-02-10 21:21 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/EventComponents/FollowingEvents.tsx
> +    const numberOfFollowingEvents = 3;
à sortir au-dessus en tant que constante: NUMBER_OF_FOLLOWING_EVENTS

2021-02-10 21:24 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/EventComponents/FollowingEvents.tsx
> +    const numberOfFollowingEvents = 3;
dans un fichier constants.ts dans /lib

2021-02-10 21:24 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/EventComponents/FollowingEvents.tsx
> +    const followingEventsWithoutPageEvent = followingEvents.filter((followingEvent) => followingEvent.id !== event.id);
nextEventsWithoutCurrentEvent

2021-02-10 21:31 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/EventComponents/FollowingEvents.tsx
> +  };
`const eventsWithoutCurrentEvent = events.filter(e => e.id !== event.id);
return eventsWithoutCurrentEvent.slice(0, NUMBER_OF_FOLLOWING_EVENTS)
`

2021-02-10 21:34 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +  const [numberOfArticlesToDisplay, setNumberOfArticlesToDisplay] = useState(3);
constante

2021-02-10 21:34 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/BlogContainer.tsx
> +            onClick={() => setNumberOfArticlesToDisplay(numberOfArticlesToDisplay + 3)}
same constant

2021-02-10 21:35 UTC, Nicoowr commented on ajcf-new-site/components/Blog/BlogListComponents/SelectBlogLabels.tsx
>          <Button type="primary" onClick={() => setSelectedBlogLabel(undefined)}>
enlever undefined

2021-02-10 21:38 UTC, Nicoowr requested changes
Good :D

2021-02-13 19:36 UTC, Nicoowr requested changes
1 ptit changement et c'est good ! :D

2021-02-13 19:36 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/AgendaComponents/EventsList.tsx
> +const filterEvents = ({ selectedEventLabel, events }: filterEventsProps) => {
1 ptit changement :
- le type en PascalCase
1 rq : 
- pour 1 ou 2 arguments, tu peux les mettre à la suite au lieu de créer un type, c'est à partir de 3 qu'il faut faire un type. mais tu peux laisser comme ça ici

2021-02-13 19:36 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/EventComponents/NextEvents.tsx
> +const filterNextEvents = ({ currentEvent, events }: FilterNextEventsProps) => {
Perfect :D

2021-02-14 01:29 UTC, seimori commented on ajcf-new-site/components/Agenda/AgendaComponents/EventsList.tsx
> +const filterEvents = ({ selectedEventLabel, events }: filterEventsProps) => {
Oups! Je l'oublie souvent le PascalCase.
Il y a un réglage (d'ESlint par exemple?) qui me permettrait d'être signalé quand je n'utilise pas le bon type de casse?

2021-02-14 01:30 UTC, seimori commented on ajcf-new-site/components/Agenda/AgendaComponents/EventsList.tsx
> +const filterEvents = ({ selectedEventLabel, events }: filterEventsProps) => {
Oh okay, à partir de 3 je note.
J'avoue que je suis passé d'aucune déclaration de type à une déclaration systématique, j'avais besoin d'un repère pour ça :D

2021-02-14 09:54 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/AgendaComponents/EventsList.tsx
> +const filterEvents = ({ selectedEventLabel, events }: filterEventsProps) => {
ah si y a ça ! je vais la faire passer sur master :)

2021-02-14 09:54 UTC, merged

2021-02-14 09:56 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/AgendaComponents/EventPreview.tsx
> +        {additionalEventLabels && (
du coup y a plus besoin de ça ici car `additionalEventLabels` est toujours défini (c'est un array)

2021-02-14 09:56 UTC, Nicoowr commented on ajcf-new-site/components/Agenda/AgendaComponents/EventsList.tsx
> +  selectedEventLabel: EventLabel | undefined;
? à la place de undefined

2021-02-14 09:58 UTC, Nicoowr commented
bon jai mergé 
j'étias mal réveillé xD

2021-02-14 17:08 UTC, seimori commented
> bon jai mergé
> j'étias mal réveillé xD

Oh j'ai pas bien suivi, il s'est passé quoi? :D