eng: Functional Breadcrumbs (needs styling)
lajcf/ajcf pull request #86
Opened 2021-02-10 21:40 UTC by seimori

2021-02-10 21:41 UTC, Nicoowr commented on ajcf-new-site/pages/projets-ajcf/nos-espaces.tsx
> +export default function nosEspaces() {
PascalCase

2021-02-10 21:45 UTC, Nicoowr commented on ajcf-new-site/pages/a-propos/qui-sommes-nous.tsx
> +export default function quiSommesNous() {
PascalCase

2021-02-10 21:52 UTC, Nicoowr commented on ajcf-new-site/components/Layout/Breadcrumbs/Breadcrumbs.tsx
> +  if (!pathArray[1]) {
dans container
de même pour articles & events

2021-02-10 21:52 UTC, Nicoowr commented on ajcf-new-site/components/Layout/Breadcrumbs/Breadcrumbs.tsx
> +  if (!pathArray[1]) {
if (pathArray.length === 1)

2021-02-10 21:59 UTC, Nicoowr commented on ajcf-new-site/components/Layout/Breadcrumbs/BreadcrumbsContainer.tsx
> +  const pathArray = pathname.split("/");
const pathSplitArray

2021-02-10 22:07 UTC, Nicoowr commented on ajcf-new-site/components/Layout/Breadcrumbs/Breadcrumbs.tsx
> +  if (!pathArray[1]) {
créer une `const pathSplitWithoutHome = pathArray.slice(1);`

2021-02-16 20:46 UTC, lajcf commented on ajcf-new-site/components/Layout/Breadcrumbs/BreadcrumbsContainer.tsx
> +const pageLink = (index: number, breadcrumbsPathArray: string[]) => {
export 
import dans Breadcrumbs

2021-02-16 20:47 UTC, lajcf requested changes

2021-02-16 20:47 UTC, lajcf commented on ajcf-new-site/components/Layout/Breadcrumbs/BreadcrumbsContainer.tsx
> +const pageLink = (index: number, breadcrumbsPathArray: string[]) => {
descendre

2021-02-17 15:16 UTC, lajcf approved these changes

2021-02-17 15:16 UTC, merged